### ISSUE TITLE
Добавить новый класс Wizard

### ISSUE THREAD

**Issue by Kangern** [Shavius/test_site#28]
### Discussed in https://github.com/Shavius/test_site/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **Legrendorg** November  1, 2024</sup>
Может Добавить новый класс Wizard ?</div>

**Comment by Tolgran** [comment]
ok

**Comment by Legrendorg** [comment]
Норм

**Comment by Tolgran** [comment]
Народ может я напишу класс WIzard ?

**Comment by Shavius** [comment]
> Народ может я напишу класс WIzard ?

Я только ЗА!
