### ISSUE TITLE
Добавить в Main-LTBD.yml - Переменную а не фиксированное значение

### ISSUE THREAD

**Issue by Tolgran** [Shavius/test_site#90]
Добавить в Main-LTBD.yml - Переменную а не фиксированное значение для условия:

* `if: github.event_name == 'pull_request' && github.repository == 'Shavius/test_site'`
* `if: github.event_name == 'push' && github.repository == 'Shavius/test_site'`
* Например: `${{ REPOSITORY_NAME }}`
* И потом использовать эту переменную в своем репозитории.

**Comment by Shavius** [comment]
Неплохая идея, так и зделаю. 🥇
